// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv8LKlaq_JuTZVKMVPv_rNaYdh--K57aM',
    appId: '1:960197562235:web:c8b9f07a9573e3a64637de',
    messagingSenderId: '960197562235',
    projectId: 'skripsi-742b2',
    authDomain: 'skripsi-742b2.firebaseapp.com',
    databaseURL: 'https://skripsi-742b2-default-rtdb.firebaseio.com',
    storageBucket: 'skripsi-742b2.firebasestorage.app',
    measurementId: 'G-8CWK407H6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqAFG-YdqaZplNru3Ba_HqtQF2UtL-54',
    appId: '1:960197562235:android:62335753a3c95bcf4637de',
    messagingSenderId: '960197562235',
    projectId: 'skripsi-742b2',
    databaseURL: 'https://skripsi-742b2-default-rtdb.firebaseio.com',
    storageBucket: 'skripsi-742b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6pype57ZJHHbbrKR_HU6b16HYJu0Tybc',
    appId: '1:960197562235:ios:43cf99beb08755da4637de',
    messagingSenderId: '960197562235',
    projectId: 'skripsi-742b2',
    databaseURL: 'https://skripsi-742b2-default-rtdb.firebaseio.com',
    storageBucket: 'skripsi-742b2.firebasestorage.app',
    iosBundleId: 'com.example.skripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6pype57ZJHHbbrKR_HU6b16HYJu0Tybc',
    appId: '1:960197562235:ios:43cf99beb08755da4637de',
    messagingSenderId: '960197562235',
    projectId: 'skripsi-742b2',
    databaseURL: 'https://skripsi-742b2-default-rtdb.firebaseio.com',
    storageBucket: 'skripsi-742b2.firebasestorage.app',
    iosBundleId: 'com.example.skripsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv8LKlaq_JuTZVKMVPv_rNaYdh--K57aM',
    appId: '1:960197562235:web:ef1dd2d2cf8b30094637de',
    messagingSenderId: '960197562235',
    projectId: 'skripsi-742b2',
    authDomain: 'skripsi-742b2.firebaseapp.com',
    databaseURL: 'https://skripsi-742b2-default-rtdb.firebaseio.com',
    storageBucket: 'skripsi-742b2.firebasestorage.app',
    measurementId: 'G-HYSR89DGB3',
  );
}
